doc: Add Prometheus and Grafana integration to MONITORING
l7mp/stunner pull request #63
Opened 2023-01-17 20:57 UTC by levaitamas

Based on PR #51.

Comments are welcome.

2023-01-18 14:58 UTC, rg0now requested changes
Apart from some short comments I'm fine with the PR, thanks. The comments:
- Why do we put the configuration part (PodMonitor config) first, and only after that installation part (stunner-prometheus helm chart)? For me the straightforward order of the subsections would be Installation, Configuration, Test, with these titles. 
- From the description it is not clear to me whether it is the user's responsibility to create the PodMonitor resource or it it automatically done by the helm chart.
- I love the screenshots but can we maybe highlight a case where there is an actual reading in the plot instead of the boring line at zero? Why not performing the iperf test (simple-tunnel) and then presenting the packet counter or the byte counter screenshots?

2023-01-26 12:38 UTC, levaitamas commented
@rg0now that was spot on, thanks!

I did a major rewrite: combined the Prometheus and Grafana integration into a single section with the subsections as *Installation*, *Configuration and Usage*, and *Troubleshooting*. The focus is shifted to the helm chart-based install and to Grafana visualization.

Installation focuses on the helm chart only -- omitted the PodMonitor configuration part to keep the focus on the helm chart-based install.

Configuration and Usage shows how to visualize STUNner metrics in Grafana: how to add new plots and how to use it.

Troubleshooting gives pointers to checking the path of metrics from STUNNer to Prometheus, and from Prometheus to Grafana.

Screenshots are in sync with current metrics and show some real traffic.

wdyt?

2023-01-31 17:37 UTC, rg0now approved these changes

2023-01-31 17:38 UTC, merged

2023-01-31 17:38 UTC, rg0now commented
Thanks a lot, applied